### ISSUE TITLE
Files paths are wrong on `helm-resume`

### ISSUE THREAD

**Issue by xiongtx** [cosmicexplorer/helm-rg#11]
## Problem

Calling `helm-rg` and visiting a file is fine. On `helm-resume` and visiting a file, however, the path is wrong. 

The project directory is not prepended to the path of the resumed candidate, resulting in e.g. a new `README.md` being created at the system root instead of visited at the project root.

**Comment by cosmicexplorer** [comment]
#14 should fix this once merged. Thank you for raising this issue!

**Comment by cosmicexplorer** [comment]
This should be fixed with #14 ([a test was also added](https://github.com/cosmicexplorer/helm-rg/blob/2cac4b6f9ab16962d63003c3f8b07e4d4f9899db/tests/helm-rg-test.el#L69) to avoid regressions), although I need to fix the current CI issue. Please reopen this if the issue reoccurs or occurs differently.
