### ISSUE TITLE
Don't kill `*helm-rg*` buffer after `helm-rg`

### ISSUE THREAD

**Issue by xiongtx** [cosmicexplorer/helm-rg#4]
`helm-rg--unwind-cleanup` kills the `*helm-rg*`  buffer after invocation of `helm-rg`. This prevents `helm-resume` from working.

`helm-resume` can resume a previous Helm session without re-running the command, allowing the user to pick up where they left off. This can be useful when it's not clear which of several search results is the one desired.

**Comment by cosmicexplorer** [comment]
I just pushed 87c09d58f427be9b3fb82d6855f9f76499eee2de, which *should* do the trick. I left a TODO because this sort of thing deserves a test. I plan to invest a little more time developing "bounce mode" before adding testing, but it's something I've done before and shouldn't take too long after that. If there are further interactions with other packages I should fix or note, please let me know! Thanks for the clear and detailed issue.

**Comment by xiongtx** [comment]
Looks good!
